pipeline:
  name: remote-pipeline-repo2
  identifier: remotepipelinerepo2
  template:
    templateRef: pipelinefeaturerepo1
    versionLabel: v2
    gitBranch: new2
    templateInputs:
      stages:
        - stage:
            identifier: p1
            template:
              templateInputs:
                type: Custom
                variables:
                  - name: s1
                    type: String
                    value: <+input>
                  - name: s2
                    type: String
                    value: fixed
  tags: {}
  projectIdentifier: kanikatest
  orgIdentifier: default
